# Generated by Django 4.2 on 2023-04-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_toping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='toping',
        ),
    ]
