# Generated by Django 4.2 on 2023-08-21 06:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameFile', models.TextField(null=True)),
                ('File', models.FileField(upload_to=api.models.upload_to)),
                ('UserToken', models.TextField(default='')),
            ],
            options={
                'ordering': ['NameFile'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameNote', models.TextField(null=True)),
                ('DescriptionNote', models.TextField(null=True)),
                ('UserToken', models.TextField(default='')),
            ],
            options={
                'ordering': ['NameNote'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTask', models.TextField(null=True)),
                ('DescriptionTask', models.TextField(null=True)),
                ('DateTask', models.DateField(auto_now_add=True)),
                ('FileForTask', models.FileField(upload_to=api.models.upload_to)),
                ('UserToken', models.TextField(default='')),
            ],
            options={
                'ordering': ['NameTask'],
            },
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Dessert',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
