# Generated by Django 4.2 on 2023-08-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_file_note_task_delete_coffee_delete_dessert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Subtasks',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
