# Generated by Django 4.2 on 2023-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_task_subtasks_delete_order_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameSubTasks', models.TextField(null=True)),
                ('DescriptionSubTasks', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='Subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='SubTasks',
            field=models.ManyToManyField(to='api.subtasks'),
        ),
    ]
