# Generated by Django 4.2 on 2023-08-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_subtasks_remove_task_subtasks_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SubTasks',
            field=models.ManyToManyField(null=True, to='api.subtasks'),
        ),
    ]
