# Generated by Django 4.2 on 2023-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SubTasks',
            field=models.ManyToManyField(db_constraint=False, null=True, to='api.subtasks'),
        ),
    ]
