# Generated by Django 4.2 on 2023-08-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_task_subtasks_task_statustask_delete_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserToken', models.TextField(default='')),
                ('NameGroupTask', models.TextField(null=True)),
                ('StatusGroupTask', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['NameGroupTask'],
            },
        ),
    ]
