# Generated by Django 4.2 on 2023-08-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_grouptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskForGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserToken', models.TextField(default='')),
                ('NameTaskForGroup', models.TextField(null=True)),
                ('DescriptionTask', models.TextField(null=True)),
                ('StatusTaskForGroup', models.BooleanField(default=False)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grouptask')),
            ],
            options={
                'ordering': ['NameTaskForGroup'],
            },
        ),
    ]
