# Generated by Django 5.0.3 on 2024-03-10 09:40

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_taskforgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandsDescription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CosmeticName', models.TextField(default='')),
                ('CosmeticDescription', models.TextField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('UrlsImage', models.ImageField(default='', upload_to=api.models.upload_to)),
                ('IsItNew', models.BooleanField(default='')),
                ('Brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brands')),
            ],
        ),
    ]
