# Generated by Django 5.0.3 on 2024-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_brands_cosmetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserToken', models.TextField(default='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('PendingDeprecationWarningrice', models.IntegerField(null=True)),
                ('Product', models.ManyToManyField(to='api.cosmetic')),
            ],
            options={
                'ordering': ['UserToken'],
            },
        ),
    ]
