# Generated by Django 5.0.3 on 2024-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_file_remove_taskforgroup_group_delete_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.TextField(null=True)),
                ('Translation', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cosmetic',
            name='Brands',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Cosmetic',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
